version: '3.9'
services:
  sqlserver:
    container_name: SQL-Server
    hostname: sql-server
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "12345OHdf%e"
    # Les données de la base seront ainsi persistantes
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - sql-server

  web:
    container_name: Web-Server
    image: php:8-apache
    ports:
      - "80:80"
    volumes:
      - app:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - jokes-manager-project

volumes:
  dbdata:
  app:

networks:
  jokes-manager-project: