version: '3.9'
services:
  sqlserver:
    container_name: SQL-Server
    hostname: sql-server
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "12345OHdf%e"
      MSSQL_SA_PASSWORD: "12345OHdf%e"
      MSSQL_PID: "Developer"
    networks:
      - sql-server

networks:
  sql-server: