version: '3.9'
services:
  sqlserver:
    container_name: SQL-Server
    hostname: sql-server
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "12345OHdf%e"
    networks:
      - sql-server

networks:
  sql-server: